services:
  openstack-reporter:
    # image: ghcr.io/vasyakrg/openstack-reporter:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
        - GIT_COMMIT=${GIT_COMMIT}
        - BUILD_TIME=${BUILD_TIME}
    ports:
      - "8080:8080"
    environment:
      - OS_PROJECT_DOMAIN_NAME=${OS_PROJECT_DOMAIN_NAME}
      - OS_USER_DOMAIN_NAME=${OS_USER_DOMAIN_NAME}
      - OS_USERNAME=${OS_USERNAME}
      - OS_PASSWORD=${OS_PASSWORD}
      - OS_AUTH_URL=${OS_AUTH_URL}
      - OS_IDENTITY_API_VERSION=${OS_IDENTITY_API_VERSION}
      - OS_AUTH_TYPE=${OS_AUTH_TYPE}
      - OS_INSECURE=${OS_INSECURE}
      - OS_REGION_NAME=${OS_REGION_NAME}
      - OS_PROJECT_NAME=${OS_PROJECT_NAME}
      - PORT=8080
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/status",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro # SSL certificates
    depends_on:
      - openstack-reporter
    restart: unless-stopped
    profiles:
      - production
