# Production values for openstack-reporter
replicaCount: 1

image:
  repository: ghcr.io/vasyakrg/openstack-reporter
  pullPolicy: Always
  tag: "v1.0.30"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: openstack-reporter.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: openstack-reporter-tls
      hosts:
        - openstack-reporter.yourdomain.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  storageClass: "fast-ssd"
  accessMode: ReadWriteOnce
  size: 10Gi

# OpenStack configuration - replace with your actual values
openstack:
  auth:
    authUrl: "https://your-openstack-auth-url:5000/v3"
    username: "your-username"
    password: "your-password" # This will be stored in a secret
    projectName: "your-project"
    projectId: "your-project-id"
    domainName: "your-domain"
    regionName: "your-region"

config:
  collectionInterval: 15
  maxBackups: 30
  logLevel: "info"
