name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build binaries
        run: |
          make build-all

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          body: |
            # OpenStack Reporter ${{ github.ref_name }}

            ## Docker Image

            ```bash
            docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ```

            ## Quick Start

            ```bash
            # Set your OpenStack credentials
            export OS_PROJECT_DOMAIN_NAME=your-domain
            export OS_USER_DOMAIN_NAME=your-domain
            export OS_USERNAME=your-username
            export OS_PASSWORD=your-password
            export OS_AUTH_URL=https://your-openstack-endpoint:5000/v3
            export OS_IDENTITY_API_VERSION=3
            export OS_AUTH_TYPE=password
            export OS_INSECURE=true

            # Run the application
            docker run -p 8080:8080 \
              -e OS_PROJECT_DOMAIN_NAME \
              -e OS_USER_DOMAIN_NAME \
              -e OS_USERNAME \
              -e OS_PASSWORD \
              -e OS_AUTH_URL \
              -e OS_IDENTITY_API_VERSION \
              -e OS_AUTH_TYPE \
              -e OS_INSECURE \
              ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ```

            ### Binary files

            - **Linux**: `amd64`, `arm64`
            - **macOS**: `amd64`, `arm64`

            Скачайте с этой страницы релиза и запустите локально.
          files: |
            bin/openstack-reporter-linux-amd64
            bin/openstack-reporter-linux-arm64
            bin/openstack-reporter-darwin-amd64
            bin/openstack-reporter-darwin-arm64
          draft: false
          prerelease: false
